### ISSUE TITLE
Improvement request

### ISSUE THREAD

**Issue by oitsuki** [maximerenou/php-hugging-chat#4]
Hello,
It's not an issue but an improvment if it's possible.

I tried your approach and I would know if  can delete some words when some element from the answer:
example:
Question : Can you translate in French : Give me a SEO Title in less 50 characters about : : Iphone
Answer : Sure, here is a possible translation: "Top iPhone XS Max features for gaming" (43 characters) Let me know if you would like any further assistance.
Good approach : Top iPhone XS Max features for gaming
 
 Else I  suppose the model does have the capacities to translate in french
 
 Thank you

**Comment by maximerenou** [comment]
Hello,

You should try the other way around: asking the model to write the answer exactly the way you want it (in other words, **prompt engineering**)

This package is only a generic adapter for HuggingChat’s models. But I hope it helps!
