### ISSUE TITLE
Conversation.php fails to "init" for hugging-chat and bing-ai

### ISSUE THREAD

**Issue by 0x004a** [maximerenou/php-hugging-chat#5]
Hugging Chat is line: 87
Bing AI is line: 104

Any idea why it's stopped working, since last 2 days?
(Tried from different IP addresses in case it was a blocking issue.)

**Comment by maximerenou** [comment]
Hello,

Bing is working well, please check that your cookie is still valid!

HuggingChat made a huge change (v0.2 requires authentication) so I'll have to update this repo.

Stay in touch

**Comment by 0x004a** [comment]
Can confirm that Bing is still working. Brilliant!
