### ISSUE TITLE
initConversation Error

### ISSUE THREAD

**Issue by tanabem** [maximerenou/php-hugging-chat#7]
Hi All,

After installing the latest version of php-hugging-chat-0.5.2, when starting "chat.php" in the example directory, the following error is output.
”PHP Fatal error: Uncaught Exception: Failed to init conversation in /var/www/html/php-hugging-chat-0.5.2/src/Conversation.php:87”

The error message tells us that the "Failed to init conversation" error occurred on line 87 of his Conversation.php. And this shows that the exception is thrown inside the initConversation method of the Conversation object.

Could you tell me how to deal with this?

Best regards,
Minoru Tanabe

**Comment by maximerenou** [comment]
Hello,

I'm sorry but this package is deprecated as discussed in #6 
It cannot deal with HuggingChat API since they added authentication.

Greetings
